version: "3.8"

services:
  back-end:
    build: ./back-end
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - TEST_DATABASE_URL=postgres://postgres:password@test-database:5432/postgres
    depends_on:
      - database
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /app
        - action: rebuild
          path: back-end/package.json

  web-app:
    build:
      context: ./web-app
      target: dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /app
        - action: rebuild
          path: web-app/package.json

  database:
    image: postgres:15
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  test-database:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  database-data:
