import {
  BUS_COLOR_CODE,
  CARBONE_COLOR_CODE_1,
  CARBONE_COLOR_CODE_2,
  CARBONE_COLOR_CODE_3,
  CARBONE_COLOR_CODE_4,
  CARBONE_COLOR_CODE_5,
  CARBONE_COLOR_CODE_6,
  CARBONE_COLOR_CODE_7,
  CARBONE_COLOR_CODE_8,
  CARBONE_COLOR_CODE_9,
  CARBONE_COLOR_CODE_NO_DATA,
  CAR_COLOR_CODE,
  PLANE_COLOR_CODE,
  TRAIN_COLOR_CODE,
} from "@/styles/constants";
import {
  WORLD_EMISSIONS_BREAKPOINT_1,
  WORLD_EMISSIONS_BREAKPOINT_2,
  WORLD_EMISSIONS_BREAKPOINT_3,
  WORLD_EMISSIONS_BREAKPOINT_4,
  WORLD_EMISSIONS_BREAKPOINT_5,
  WORLD_EMISSIONS_BREAKPOINT_6,
  WORLD_EMISSIONS_BREAKPOINT_7,
  WORLD_EMISSIONS_BREAKPOINT_8,
} from "./constants";
import { color } from "@mui/system";

export const MAP_LEGEND_ELEMENTS = [
  { label: `< ${WORLD_EMISSIONS_BREAKPOINT_1}`, color: CARBONE_COLOR_CODE_1 },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_1} - ${WORLD_EMISSIONS_BREAKPOINT_2}`,
    color: CARBONE_COLOR_CODE_2,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_2} - ${WORLD_EMISSIONS_BREAKPOINT_3}`,
    color: CARBONE_COLOR_CODE_3,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_3} - ${WORLD_EMISSIONS_BREAKPOINT_4}`,
    color: CARBONE_COLOR_CODE_4,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_4} - ${WORLD_EMISSIONS_BREAKPOINT_5}`,
    color: CARBONE_COLOR_CODE_5,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_5} - ${WORLD_EMISSIONS_BREAKPOINT_6}`,
    color: CARBONE_COLOR_CODE_6,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_6} - ${WORLD_EMISSIONS_BREAKPOINT_7}`,
    color: CARBONE_COLOR_CODE_7,
  },
  {
    label: `${WORLD_EMISSIONS_BREAKPOINT_7} - ${WORLD_EMISSIONS_BREAKPOINT_8}`,
    color: CARBONE_COLOR_CODE_8,
  },
  { label: `> ${WORLD_EMISSIONS_BREAKPOINT_8}`, color: CARBONE_COLOR_CODE_9 },
  { label: "no data", color: CARBONE_COLOR_CODE_NO_DATA },
];

export const STATISTICS_LEGEND_ELEMENTS = [
  { label: "train", color: TRAIN_COLOR_CODE },
  { label: "bus", color: BUS_COLOR_CODE },
  { label: "voiture", color: CAR_COLOR_CODE },
  { label: "avion", color: PLANE_COLOR_CODE },
];
