export const WORLD_EMISSIONS_BREAKPOINT_1 = 0.1;
export const WORLD_EMISSIONS_BREAKPOINT_2 = 0.2;
export const WORLD_EMISSIONS_BREAKPOINT_3 = 0.5;
export const WORLD_EMISSIONS_BREAKPOINT_4 = 1;
export const WORLD_EMISSIONS_BREAKPOINT_5 = 2;
export const WORLD_EMISSIONS_BREAKPOINT_6 = 5;
export const WORLD_EMISSIONS_BREAKPOINT_7 = 10;
export const WORLD_EMISSIONS_BREAKPOINT_8 = 20;

export const WORLD_EMISSIONS_START_DATE = 1820;
export const WORLD_EMISSIONS_END_DATE = 2022;
